const
  REQUEST = 'REQUEST',
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE';

const _createRequestTypes = base =>
  [REQUEST, SUCCESS, FAILURE]
    .reduce((acc, type) => Object.assign(acc, {[type]: `${base}_${type}`}), {});

export const
  I18N_LOAD = 'I18N_LOAD',
  I18N_RECEIVE = 'I18N_RECEIVE',

  NAVIGATION_UPDATE = 'NAVIGATION_UPDATE',

  PROJECT_CLOSE = 'PROJECT_CLOSE',
  PROJECT_DELETE = _createRequestTypes('PROJECT_DELETE'),
  PROJECT_OPEN = 'PROJECT_OPEN',
  PROJECT_LOAD = 'PROJECT_LOAD',
  PROJECT_RECEIVE = 'PROJECT_RECEIVE',
  PROJECT_SAVE = _createRequestTypes('PROJECT_SAVE'),
  PROJECT_UNLOAD = 'PROJECT_UNLOAD',

  PROJECT_LIST_LOAD = 'PROJECT_LIST_LOAD',
  PROJECT_LIST_RECEIVE = 'PROJECT_LIST_RECEIVE',
  PROJECT_LIST_ADD_ITEM = 'PROJECT_LIST_ADD_ITEM',
  PROJECT_LIST_CLOSE_ITEM = 'PROJECT_LIST_CLOSE_ITEM',
  PROJECT_LIST_OPEN_ITEM = 'PROJECT_LIST_OPEN_ITEM',
  PROJECT_LIST_REMOVE_ITEM = 'PROJECT_LIST_REMOVE_ITEM',
  PROJECT_LIST_UPDATE_ITEM = 'PROJECT_LIST_UPDATE_ITEM',

  SETTINGS_LOAD = 'SETTINGS_LOAD',
  SETTINGS_RECEIVE = 'SETTINGS_RECEIVE',
  SETTINGS_UPDATE = _createRequestTypes('SETTINGS_UPDATE'),

  THEME_LOAD = 'THEME_LOAD',
  THEME_RECEIVE = 'THEME_RECEIVE';
