const
  REQUEST = 'REQUEST',
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE';

const _createRequestTypes = base =>
  [REQUEST, SUCCESS, FAILURE]
    .reduce((acc, type) => Object.assign(acc, {[type]: `${base}_${type}`}), {});

export const
  PROJECT_LIST_LOAD = 'PROJECT_LIST_LOAD',
  PROJECT_LIST_RECEIVE = 'PROJECT_LIST_RECEIVE',
  PROJECT_LIST_ADD_ITEM = 'PROJECT_LIST_ADD_ITEM',
  PROJECT_LIST_CLOSE_ITEM = 'PROJECT_LIST_CLOSE_ITEM',
  PROJECT_LIST_OPEN_ITEM = 'PROJECT_LIST_OPEN_ITEM',
  PROJECT_LIST_REMOVE_ITEM = 'PROJECT_LIST_REMOVE_ITEM',
  PROJECT_LIST_UPDATE_ITEM = 'PROJECT_LIST_UPDATE_ITEM',

  NAVIGATION_UPDATE = 'NAVIGATION_UPDATE',

  SETTINGS_LOAD = 'SETTINGS_LOAD',
  SETTINGS_RECEIVE = 'SETTINGS_RECEIVE',
  SETTINGS_UPDATE = _createRequestTypes('SETTINGS_UPDATE');
