export default {
  articleHeader: '',
  articleInput: '',
  bg: '',
  buttonNeutralLight: '',
  buttonSuccess: '',
  commonText: '',
  footerLink: '',
  footerText: '',
  informativeProjectLinkInfo: '',
  informativeProjectLinkStatus: '',
  linkActive: '',
  linkInactive: '',
  linkHover: '',
  sectionBorder: '',
  seqPanel: '',
  seqPanelSelected: '',
  seqTimelineBg: '',
  seqTimelineSelectedBg: '',
};
